### PR TITLE
Small updates to test engine

### PR DESCRIPTION
**Pull request by flooey**
Adds support for turning off verbose mode, parsing cached test results, and cleans up the config code a little bit.

### CODE REVIEW

**Comment by flooey** [comment]
Hey there, we've started using this code at work so I'm cleaning it up a little.  I know you've been looking for a maintainer and I might be in a position to take that over, but I figured I should start with some pull requests and we can see how it goes.

**Comment by flooey** [comment]
Checking in on this, any interest?

**Comment by kalbasit** [comment]
@flooey sorry for the delay somehow fell through the cracks. As I do not use this anymore, I cannot test it locally myself. Does it work for you?

**Comment by flooey** [comment]
Yep, it's been working for us, and I'm happy to fix any problems others report with it.

**Pull request closed without merging**
